FROM centos7-py36:latest

# 2.0.8
RUN yum install -y wget gcc-c++ openssl-devel openssl && \
    wget http://www.keepalived.org/software/keepalived-2.0.8.tar.gz && \
    tar zxvf keepalived-2.0.8.tar.gz && cd keepalived-2.0.8 && \
    ./configure && \
    make && \
    make install

#CMD ["keepalived", "-n","--all", "-d", "-D",  "-f", "/etc/keepalived/keepalived.conf"]